hjd1964/OnStep

- README.md
This is to add some more info to the README file, as well as link to the new wiki with more info.
> Expanding README file and including link to the new Wiki.

- Align.h
- Align.ino
This is just comment stuff, with no actual code change. It gives those who are trying to understand the code some background on the equations behind it, from Toshimi Taki himself.
> Add background comments on equations for alignment by Toshimi Taki.

- Astro.ino
- src/HAL/HAL_Mega2560/HAL_Mega2560.h
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/HAL/HAL_Teensy_3/HAL_Teensy_3.h
- src/HAL/HAL_Tiva_C/HAL_Tiva_C.h
Another file liberated from platform dependent defines.
> Cleanup of platform defines from Astro.ino, and pushing them into HAL.

- Align.ino
Typo fix, so it works as intended.
> Fixed typo in define

- OnStep.ino
- src/HAL/HAL.ino
- src/HAL/HAL_Due/HAL_Due.ino
- src/HAL/HAL_Mega2560/HAL_Mega2560.ino
- src/HAL/HAL_STM32F1/HAL_STM32F1.ino
- src/HAL/HAL_Teensy_3/HAL_Teensy_3.ino
- src/HAL/HAL_Template/HAL_Template.ino
- src/HAL/HAL_Tiva_C/HAL_Tiva_C.ino
- src/HAL/drivers/drivers.ino
Added links to documentation, github and mailing list in the OnStep.ino file, so anyone opening it can access those.
Also better comments in placeholder files.
> Links to documentation, github and mailing list 

- src/addons/WiFi-Bluetooth/README.md
Added some more information, as I am doing stuff.
> Better documentation for flashing ESP8266

- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/pinmaps/Pins.STM32Black.h
Staying away from LED pin, and pins for I2C and Serial2
> I2C EEPROM finally working, and some pin improvements for Black Pill board.

- addons/WiFi-Bluetooth/README.md
- src/pinmaps/Pins.STM32B.h
Update documentation for WiFi with correct pins.
> Correct pins for STM32

- src/HAL/HAL_STM32F1/HAL_STM32F1.h
Eliminated code that affects timing precision.  This improves tracking accuracy on STM32.
> Improve tracking accuracy on STM32

- addons/St4Serial/SmartHandController/SHC_Config.h
- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/Telescope.cpp
- addons/St4Serial/SmartHandController/Telescope.h
Sidereal was misspelled as Sideral
> Fix mispelling in code and in display

- addons/St4Serial/SmartHandController/LX200.cpp
- addons/St4Serial/SmartHandController/SmartController.cpp
'Tracking' is now under the main menu, rather than being a 'Setting' thing.
> Move Tracking to the main menu rather than being buried under Settings

- README.md
In case someone wants a detailed change log, they can get it from git, with the command in the README file.
> Alpha: Adding command to get change log from git.

- README.md
In case someone wants a detailed change log, they can get it from git, with the command in the README file.
> Beta: add git command for change log

- addons/St4Serial/SmartHandController/README.md
Some changes to the README.md file for the SHC.
> README.md changes

- .gitignore
- addons/WiFi-Bluetooth/Config.h
- addons/WiFi-Bluetooth/Index.ino
Reads the wifi RSSI, calculates signal strength in percent and reports via web interface. It has been tested in AP mode only.
This is my first pull request. I hope i did all ok.  If you find it useful merge it with Onstep, please. If not scrap it.
> Wifi-Bluetooth addon - show Wifi signal strength on index page

- addons/St4Serial/SmartHandController/Catalog.cpp
- addons/St4Serial/SmartHandController/Catalog.h
- addons/St4Serial/SmartHandController/SmartHandController.ino
- addons/St4Serial/SmartHandController/Telescope.cpp
- Clean up the code that checks for below horizon objects, so as not to show them when scrolling through the menus
- Eliminate multiplication and division by magic values
- Encapsulate calculations, so one function does one thing in always consistent units.
> Correct calculation for objects below horizon

- Astro.ino
- addons/St4Serial/SmartHandController/SmartController.cpp
Make SHC compile again when no Aux port enabled.
> Make SHC compile when no Aux port enabled

- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/Telescope.cpp
- addons/St4Serial/SmartHandController/Telescope.h
Not sure if this is the best way how to do it. Please review. Thanks
> Shows different icons for Sidereal, Lunar and Solar tracking rate

- Command.ino
- src/lib/Heater.h
Hello,
I have added commands for heaters (compile, but not yet tested).
Commands:
:SXL1,-3#   set heater 1 Low Delta C (at or below -3C is 100% power)
:GXL1#       returns -3
:SXH1,15#  set heater 1 High Delta C (at or above 15C is 0% power)
:GXH1#       returns 15#
:GXh1#       get heater 1 temperature
:SXh1,0#     turn off heater 1 (disable)
:SXh1,1#     turn on heater 1 (enable)
:Gl1#         return the actual state of heater 1 (on/off)
> Add commands for heaters

- src/HAL/HAL.h
- src/HAL/HAL_Due/HAL_Due.h
- src/HAL/HAL_Due/HAL_Due.ino
- src/pinmaps/Pins.Ramps14.h
Added  support for Arduino DUE board
> Added Arduino DUE HAL

- addons/Ethernet/Auxiliary.ino
- addons/Ethernet/CmdServer.ino
- addons/Ethernet/Config.h
- addons/Ethernet/Configuration.ino
- addons/Ethernet/Constants.h
- addons/Ethernet/Control.ino
- addons/Ethernet/Encoders.ino
- addons/Ethernet/Ethernet.ino
- addons/Ethernet/Library.ino
- addons/Ethernet/PEC.ino
- addons/Ethernet/Settings.ino
- addons/Ethernet/WebServer.ino
Here is the new and improved Ethernet addon.  It has the following fixes / changes from the Master release:
1) Runs on Teensy 3.2 and Teensy 4.0 with no crashes that I have found.  If you cause one, please document the exact sequence of moves you make to get there.
2) Works with all of the new advanced features for changing parameters for the next boot if you are running the Master OnStep release.
3) The Ethernet USB port is a valid debug port, you can get local debugging prints using DebugSer.print().  Central logging of debugging is also available using Howard's macros.
4) Runs fast enough with the Teensy 4.0 to keep up with virtually any encoders (mine are 311,000 plus steps and they track the gotos perfectly).
> Fixes to make Teensy 3.2 and 4.0 work with Ethernet addon. 
