- OnStep.ino
The PPS Interrupt did not work on my Teensy. Teensyduino seems to need the explicit setting of pinMode to INPUT
> Fixing PPS Interrupt on Teensy

- Command.ino
- Config.h
- EEPROM_LP.h
- EEPROM_LP.ino
- Library.ino
- Network.ino
- OnStep.ino
- Serial.ino
- Timer.ino
Added support for TI Tiva Launchpad TM4C123 and TI Tiva Connected Launchpad TM4C129
Added Ethernet for the Connected Launchpad
Some things require clarifications:
1. Most of the new code is within the newly added
#if defined(__TM4C123GH6PM__) || defined(__LM4F120H5QR__)
and
#if defined(__TM4C1294NCPDT__) || defined(__TM4C1294XNCZAD__)
each for one of the two Launchpads (the TM4C123 was released in two revisions).
My changes should not affect any of the code Arduino/Teensy, however, read carefully point 7 below before trying to compile.
2. Wherever possible I have shared the code with Teensy. For example, all timer calculations are using the Teensy code. The major difference is how timers are configured and started for the two devices. Energia does not support IntervalTimer so all timers …
> Arduino mega2560 teensy3.1 alpha

- Command.ino
This fixes the issue of the OnStep INDI driver not being able to connect when using the Serial 1 interface (usually bluetooth). The problem is described in the INDI forum at http://www.indilib.org/forum/wish-list/1406-driver-onstep-lx200-like-for-indi.html?start=18.
Thanks,
Ben
> Fix <ACK> command from Serial1.

- Pins.STM32.h
- src/HAL/HAL.h
Correct unused pins free on the board for axis 1 and axis 2. 
Added comments on which boards compiled successfully, and which need pin changes.
> Correct pins for axis 1 and 2. Comments on STM32 boards

- Config.STM32.h
- Constants.h
- Validate.h
The Constants.h file should be included only once. 
There should be no conditional defines in it either, since no configs have been included yet.
Even though the defines are mostly for AXISn_MICROSTEPS, then do nothing if that new configuration is used. They are just defines and declarations.
Tested to compile on all platforms (except Tiva C).
> Constants.h include file should be included only once

- src/HAL/HAL_Due/HAL_Due.h
- src/HAL/drivers/HAL_24LC256.h
This is to generalize the 24LC library in src/HAL/drivers. 
By making E2END mandatory in the calling HAL_x.h, we can reuse the 24LC library in other platforms transparently.
> Make E2END definition in the calling HAL_x.h mandatory

- Config.STM32.h
- Pins.STM32.h
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/HAL/drivers/HAL_24LC.h
STM32F103C8T6 Black Pill support. Preliminary. Includes changes to the I2C EEPROM HAL driver to be able to pass a different address for the EEPROM.
> STM32F103C8T6 Black Pill support, with I2C EEPROM via DS3231 module

- Config.STM32Black.h
- Config.STM32CZ.h
- OnStep.ino
- Validate.h
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/HAL/drivers/NV_I2C_EEPROM.h
- src/lib/NV.h
- src/pinmaps/Pins.STM32Black.h
- src/pinmaps/Pins.STM32CZ.h
Added different pinouts for CZ Mini (STM32F103VE) and Black Pill (STM32F103C8). The former has quite a few more pins than the latter. Some pin names do not even exist in the other (due to having the pins in groups, A, B, C, ...etc., and medium density MCU not having them all).
Also added here is a self contained NV API for I2C EEPROM. It does not require including EEPROM.h, like HAL_24LC.h does. EEPROM.h on STM32 is flash emulation and that confuses things. The NV_I2C_EEPROME preserves the behaviour for other platforms. The NV.h file will be included, but none of the code in it will be preprocessed nor compiled, just like system headers have checks to not include files more than once. 
The NV_I2C_EEPROM works with a standalone test program that prints the contents of EEPROM and then …
> STM32 variants: CZ Mini board and Black Pill

- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/pinmaps/Pins.STM32CZ.h
Stay away from officially assigned pins (as much as practical), and use Serial2 for CZ Mini board, which has a connector for ESP-01.
> Change pins, and WiFi Serial USART

- Command.ino
- Config.Classic.h
- Config.MaxPCB.h
- Config.Mega2560Alt.h
- Config.MiniPCB.h
- Config.Ramps14.h
- Config.TM4C.h
- Guide.ino
- OnStep.ino
- Validate.h
- addons/WiFi-Bluetooth/README.md
- src/HAL/HAL_Due/HAL_Due.h
- src/HAL/HAL_Mega2560/HAL_Mega2560.h
- src/HAL/HAL_Mega2560/HAL_Serial.h
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/HAL/HAL_Teensy_3/HAL_Teensy_3.h
- src/HAL/HAL_Template/HAL_Template.h
- src/HAL/HAL_Tiva_C/HAL_Tiva_C.h
- src/lib/St4SerialMaster.h
- src/pinmaps/Pins.STM32Black.h
- src/pinmaps/Pins.STM32CZ.h
Use A, B, C for serial ports. B and C can be assigned to Serial1, Serial4, Serial7, ...etc. depending on the platform. 
No confusion for those checking HAL or OnStep's source code.
> Decouple serial port names from their hardware number, get WiFi working on STM32

- Config.STM32.h
- Validate.h
- src/pinmaps/Pins.STM32B.h
The Blue Pill is the predecessor of the Black Pill. It has 2 more pins, and some pins are 5V tolerant. 
Support is added via the same pinmap file.
> Support for the Blue Pill STM32 board.

- src/pinmaps/Pins.STM32B.h
Since the hardware SPI pins are not needed for the TMC2130 (it uses SoftSPI), we have a few spare pins, and can re-purpose the SPI ones.
Also, a focuser needs three pins (Enable, Step and Dir), not just the latter two. 
Reworked the pinmap to account for all the above.
> Modifications to STM32 pinmap, since hardware SPI pins not required

- OnStep.ino
The flash memory storage problem is back in the latest Alpha.
The code here fixes it and OnStep flashes and works again.
> Using 'static ... = foo();' causes STM32 to overflow flash memory.

- OnStep.ino
- src/HAL/HAL_Due/HAL_Due.h
- src/HAL/HAL_Mega2560/HAL_Mega2560.h
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
- src/HAL/HAL_Teensy_3/HAL_Teensy_3.h
- src/HAL/HAL_Template/HAL_Template.h
- src/HAL/HAL_Tiva_C/HAL_Tiva_C.h
On the STM32, we need a call to a platform specific function that disables the reservation of certain pins for debugging. This means that the pins are reclaimed and reusable again. 
Implemented in a way that allows any platform to have init functions that are specific to it, in the HAL_platform.h file.
> New HAL_init() function, to allow platform specific initialization

- src/pinmaps/Pins.STM32B.h
Verified that all spare pins are useable. 
PEC index pin assigned.
Still cannot get focuser to work, so removed it from pinmap for now.
> Pinmap changes for STM32

- Validate.h
- src/pinmaps/Pins.STM32B.h
This prevents errors resulting from putting in an insanely large value, and points the user to use the spreadsheet to get the correct value.
> Validation of PECBufferSize

- src/pinmaps/Pins.STM32B.h
Added focuser, which works now. Yay!
Changed TONE pin to other side of the board
One spare is now RETICLE, next to the PECIDX pin, so both can be routed to the mount easily.
> STM32 Pinmap changes 

- src/pinmaps/Pins.STM32B.h
TONE and RETICLE are now on higher current pin, and PECIDX is on the low current pin.
> Moving TONE and RETICLE to pins that have higher current

- Command.ino
This adds Alignment using Plate Solving to OnStep. For example, it allows the use of Mount Model tool in KStars/Ekos.
The work flow is to start an Align in OnStep with N stars (e.g. from the INDI control panel), then use the Mount Model with that same exact number of stars, and let Ekos turn the mount around the sky and take images, plate solve them, and sync on the coordinates. 
When a sync is done (i.e. :CM# command) and OnStep detects that the alignment is in progress (i.e. number of stars aligned is not the same as number of stars selected), OnStep internally calls the AddStar align, mimicking an explicit :A+# command.
No error checking yet. 
This is tested indoors, but still untested under the stars, please test if you can.
> Allow alignment from plate solving

- Command.ino
A simple command to retrieve the raw angles for both axes. 
No conversion of degrees to RA, so easier to calculate the exact arc second.
It is very useful in scripting tests that monitor drift. 
Example:
:GR#:GD#:GXFE# produces:
2018-11-15 15:08:22 23:04:46#+15*12:18# 346.190611,15.205035#
2018-11-15 15:10:23 23:04:46#+15*12:18# 346.190396,15.205035#
2018-11-15 15:12:23 23:04:46#+15*12:18# 346.190222,15.205035#
2018-11-15 15:14:23 23:04:46#+15*12:18# 346.190007,15.205035#
2018-11-15 15:16:23 23:04:46#+15*12:18# 346.189792,15.205035#
2018-11-15 15:18:23 23:04:46#+15*12:18# 346.189590,15.205035#
2018-11-15 15:20:24 23:04:45#+15*12:18# 346.189382,15.205035#
2018-11-15 15:22:24 23:04:45#+15*12:18# 346.189153,15.205035#
2018-11-15 15:24:24 23:04:45#+15*12:18# 346.188972,15.205035#
So: …
> Added :GXFE# command to display angle for both axes.

- OnStep.ino
- Timer.ino
- src/HAL/HAL_STM32F1/HAL_STM32F1.h
This change provides the same tracking on very low Steps Per Degrees (1,777.777) GEMs, and good tracking for Alt-Az, and much better tracking on high Steps Per Degrees (28,800).
It also makes the code go back to its original form: only two code segments one for Arduino and the other for everything else. That is, there is no special segment for the STM32, duplicating portions of code.
Here are the test results. They are on Rasalhague in Ophiuchus.
4L, 120 seconds, 28,800 steps/deg, 
GEM, Khalid
3 hour test
0.065"/minute drift in RA
2018-11-16 17:58:22 03:25:28#+49*56:21# 51.366146,49.939201  0.000  0.000
2018-11-16 17:59:22 03:25:28#+49*56:21# 51.366181,49.939201  0.126  0.000
2018-11-16 18:00:23 03:25:28#+49*56:21# 51.366181,49.939201  0.063  0.000
2018-11-16 18:01:23 03:25:28#+49*56:21# …
> STM32: Changed 2L to 4L, and 40 seconds to 120 seconds

- addons/St4Serial/SmartHandController/README.md
- addons/St4Serial/SmartHandController/SHC_Config.h
- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/SmartController.h
- src/pinmaps/Pins.STM32B.h
Changed the pinmap for the STM32's ST4 port to conform to MaxPCB, MiniPCB, and MaxESP. This way, the ESP32 SHC will work for all these platforms. Verified to work.
Also Dave Schwartz made the dimming and blanking milliseconds a menu option, rather than hard coded values. . 
At least the first change needs to go into Beta, so if someone is using that, their ST4 is compatible with any SHC.
> Compatibility with other PCBs

- src/pinmaps/Pins.STM32B.h
The ST4 pinmap for STM32 was not compatible with other OnStep PCBs.
This change to Beta makes sure that an SHC will work across PCBs.
Change is already in Alpha.
> ST4 pins changes

- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/Telescope.cpp
- addons/St4Serial/SmartHandController/Telescope.h
The display said: UTC but in fact this is the correct local time, and retrieved using :GL#.
Fixed the label.
> Fix for wrong time label: it is actually local time, but labeled as UTC.

- Config.Classic.h
- Config.MaxESP2.h
- Config.MaxPCB.h
- Config.Mega2560Alt.h
- Config.MiniPCB.h
- Config.Ramps14.h
- Config.STM32.h
- OnStep.ino
- other-configurations/Config.MaxESP.h
- other-configurations/Config.TM4C.h
- src/pinmaps/Pins.STM32B.h
Adding support for Limit Sense on the STM32. 
Also, the current code does two reads of the limit pin, and waits for 50 microseconds between them.
This changes adds a tiny optimization, so only does the delay if the first attempt does detect a limit condition. 
Otherwise, the loop proceeds normally.
> More efficient detection of limits, support for Limit Sense on STM32

- addons/St4Serial/SmartHandController/Catalog.cpp
- addons/St4Serial/SmartHandController/herschel.h
- addons/St4Serial/SmartHandController/messier.h
- addons/St4Serial/SmartHandController/stars.h
> Minor changes for better conventions, and using standard C data types.

- addons/St4Serial/SmartHandController/Catalog.cpp
- addons/St4Serial/SmartHandController/LX200.cpp
- addons/St4Serial/SmartHandController/LX200.h
- addons/St4Serial/SmartHandController/MenuAlignment.h
- addons/St4Serial/SmartHandController/MenuMount.h
- addons/St4Serial/SmartHandController/MenuSettings.h
- addons/St4Serial/SmartHandController/MenuSyncGoto.h
- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/St4SerialSlave.h
- addons/St4Serial/SmartHandController/Telescope.cpp
Reinstating the previous fixes, minus the ones that caused a crash. 
Still some warnings in the u8g code, but they are harder to fix since they are many levels of indirection of calls.
> Eliminating most SHC compiler warnings.

- addons/St4Serial/SmartHandController/MenuSettings.h
- addons/St4Serial/SmartHandController/SmartController.cpp
- addons/St4Serial/SmartHandController/SmartController.h
1. Show active guide rate - perhaps top line at the left
The last selected guide rate is shown on the top line now. However if the guide rate is changed via other source than SHC it does not get updated - SHC does not read the guide rate from OnStep via LX200 command. This is not an issue for me but it can certainly be updated later on.
2. Change "Value set" messages to meaningful messages like "Unparked" e.t.c.
Parking/Unparking messages added. 
4. Set Park, Return/Reset Home - ask for confirmation (to prevent accidental triggering of model clear)
Confirmation for Set-Park added.
9. Display OnStep & SHC firmware version
Added new menu under settings that shows SHC Version / Date & Onstep Version / date.
> few changes to address  "SHC development ideas" issue

- MoveTo.ino
- Validate.h
End of slew is very slow with the 15 seconds. This was put in after KStars/Ekos users complained that precision slews would never end. I changed the 15 seconds to 5 seconds and tested precision slews, and they work well, but with a much less annoying wait.
Also, if MAX_NUM_ALIGN_STARS is defined in Config.x.h, that value will take precedence, with a warning displayed to inform the user that this may slow down alignment. This allows adventurous users to increase the number of stars if needed.
> Faster end of slew, and ability to change maximum number of stars

- Config.Classic.h
- Config.MaxESP2.h
- Config.MaxPCB.h
- Config.MiniPCB.h
- Config.Ramps14.h
- Config.STM32.h
- OnStep.ino
- Validate.h
This changes allows switches to be either of the normally open (NO) type or the normally closed (NC) variety.
Backward compatible with existing config files, i.e. default to LOW.
> Add LIMIT_SENSE_STATE to allow either LOW or HIGH states

- addons/St4Serial/SmartHandController/Pad.cpp
- addons/St4Serial/SmartHandController/Pad.h
- addons/St4Serial/SmartHandController/SmartController.cpp
Shift, f & F butons do not cancel the slew in progress. The behaviour of guiding keys (N, S, E, W) has not changed but a message is displayed that the slew was canceled.
> Shift, f & F buttons not canceling the slew

- src/lib/Weather.h
For those with 0x76 addressed BME280 modules without having to cut wires/solder their boards or make library file changes
> Enable alternate 0x76 BME280 address in the Config.h file

- Command.ino
Uppercase :FSn# command for Absolute Focuser setTarget in Microns was failing with a badCmd=true as :FS was still not expected to have a parameter during this check
> Fix for absolute focuser positioning :FSn# command

- src/pinmaps/Pins.CNC3.h
To simplify the basic 3 axis (RA/Dec/Focuser) setup using the CNC3 board. I'll redraw the pinout for this setup to update the WiKi page
> Move Axis4 to AxisZ and Axis3/5 to AxisS on CNC3 pinmap

- addons/SmartHandController/Pinmap.h
Add the analog joystic JS1 support to the Pinmap.h for the ESP32 based SHC
> Add support for JS1 on ESP32 based SHC

- src/pinmaps/Pins.Ramps14.h
V2.0 and V2.1 boards are almost identical, pinmaps change only happen on D12 -> D21, D21 -> D12 ports
This fix correctly set up M0/M1/M2/M3 pins for all axis, which is was only set correctly on Axis5 before.
Also use same pins for ST4, like on V2.0 board
> Fix MKS Gen-L V2.1 pinmaps

- addons/SmartHandController/LX200.cpp
- addons/SmartHandController/LX200.h
- addons/SmartHandController/MenuSettings.h
- addons/SmartHandController/SmartController.h
- addons/SmartHandController/Strings_en.h
These additions are almost identical to my last set of changes to add focuser TC coefficient parameter setting. The range for backlash is 0 (no backlash) to 999 (ridiculously large backlash) and the range for TC deadband is 1 (should never be 0) to 999 (another ridiculously large number). These values are in microns, but stored by the OnStep controller as steps through conversion using steps_per_micron on the way in and out.
> Changes to add Focuser backlash and TC deadband parameter setting

- src/pinmaps/Pins.FYSETC_S6.h
This was missing from my last pull request. 
Now [verified to work](https://github.com/kbahey/OnStep/archive/stm32.zip) by Dave Schwartz with TMC2130.
> Add missing port/pins for FYSETC S6 axis2 when using SPI

- Command.ino
There is everywhere documented, that :FS# command sets moving rate to 0.01mm/s, but currently it sets it to 0.001mm/s.
So there is a big difference in behavior between SHC and Android OnStep Application.
This pull request fixes this issue.
> Fixed Focuser rate for ":FS#" command to 0.01mm/s as documented.
